name: CI

on:
  push:
    branches: [ main ]

jobs:
  runTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      # Hack because I couldn't find a solution
      - name: Run the server & run the test 
        run: |
          npm run --silent start
          PID=$!
          sleep 5
          npm run --silent test
          sleep 2
          kill $PID
          kill $PID
